pipeline {
  agent {
    label 'ios-slave'
  }

  stages {
    stage('Build iOS') {
      steps {
        sh "xcodebuild -workspace ./ios/someApp/someApp.xcworkspace -scheme JenkinsCI -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' build test"
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
