pipeline {
  agent {
    docker {
      image 'chiahan1123/docker-jenkins-golang'
    }
  }

  stages {
    stage('Test Backend') {
      environment {
        GOPATH = "$WORKSPACE/backend"
      }
      steps {
        sh 'gocov test -v $(go list ./backend/... | grep -v vendor) > ./backend/coverage.json'
      }
    }
    stage('Archive Coverage Report') {
      when {
        expression {
          GIT_BRANCH = sh(returnStdout: true, script: 'git rev-parse --abbrev-ref HEAD').trim()
          return GIT_BRANCH != 'master'
        }
      }
      steps {
        sh 'gocov-html ./backend/coverage.json > ./backend/coverage.html'
      }
      post {
        success {
          archiveArtifacts 'backend/coverage.html'
        }
      }
    }
    stage('Publish Cobertura Report') {
      when {
        expression {
          GIT_BRANCH = sh(returnStdout: true, script: 'git rev-parse --abbrev-ref HEAD').trim()
          return GIT_BRANCH == 'master'
        }
      }
      steps {
        sh 'cat ./backend/coverage.json | gocov-xml > ./backend/cobertura.xml'
      }
      post {
        success {
          step([
            $class: 'CoberturaPublisher',
            autoUpdateHealth: false,
            autoUpdateStability: false,
            coberturaReportFile: 'backend/cobertura.xml',
            failUnhealthy: false,
            failUnstable: false,
            maxNumberOfBuilds: 0,
            onlyStable: false,
            sourceEncoding: 'ASCII',
            zoomCoverageChart: false
          ])
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
