pipeline {
  agent {
    docker {
      image 'chiahan1123/docker-jenkins-android'
    }
  }

  stages {
    stage('Build Android and Archive Jacoco Report') {
      steps {
        sh "gradle --stacktrace --info --refresh-dependencies -p $WORKSPACE/android/someApp clean build jacocoTestReport"
      }
      post {
        success {
          archiveArtifacts '**/android/someApp/app/build/**/jacocoTestReport/html/**/*'
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
